#
# Auto generated by makcpp
#

BIN=sxp
STD=-std=c++17
CXX=g++
OPT=-O2
WARN=-W -Wall -Wextra -pedantic
INC=-I.
LIB=-L.
LIBS=-lstdc++ -lgc -lgccpp

DEPS=sxp.hpp obj.hpp bool.hpp rt.hpp xface.hpp list.hpp str.hpp char.hpp \
     vector.hpp mapentry.hpp hashmap.hpp keyword.hpp number.hpp symbol.hpp \
     weakrefmap.hpp fn.hpp error.hpp stream.hpp var.hpp namespace.hpp \
     reader.hpp vm.hpp compiler.hpp vasm.hpp instr_8.cpp proc.hpp \
     instr_16.cpp hashset.hpp lazyseq.hpp treemap.hpp proc_ns.cpp \
     proc_numbers.cpp proc_io.cpp proc_error.cpp proc_predicate.cpp \
     treeset.hpp regex.hpp Makefile cfn.hpp proc_re.cpp

OBJ=main.o obj.o bool.o rt.o list.o str.o char.o vector.o mapentry.o \
    hashmap.o keyword.o number.o symbol.o fn.o stream.o var.o namespace.o \
    reader.o vm.o compiler.o vasm.cpp proc.o hashset.o lazyseq.o \
    treemap.o treeset.o regex.o cfn.o

%.o: %.cpp ${DEPS}
	${CXX} -c $< -o $@ ${OPT} ${WARN} ${STD} ${INC}

${BIN}: ${OBJ}
	${CXX} -o $@ $^ ${LIB} ${LIBS}

clean:
	rm -f ${BIN} *.o *~
